name: List Files on Push

on: [push]

jobs:
  list_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files
        run: ls -R