name: Lint avec PHPCS

on:
  push:
    branches:
      - mes-dates  # Sur cette branche, PHPCS sera exécuté

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Installer PHP et Composer
        run: |
          sudo apt update
          sudo apt install php php-cli php-curl
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      - name: Installer PHPCS
        run: |
          composer global require "squizlabs/php_codesniffer=*"
          export PATH=$HOME/.composer/vendor/bin:$PATH  # Ajoute PHPCS au PATH global

      - name: Exécuter PHPCS
        run: |
          phpcs --standard=PSR2 src/MesDates.php  # Vérifie le code de la classe MesDates.php avec la norme PSR2
