name: Vérification Arborescence

on:
  pull_request:
    branches:
      - master

jobs:
  check_structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Vérification de l'arborescence
        run: python .github/scripts/verif.py
